#!/usr/bin/bash

# remove container and image and rebuild image

NAME="string-forwarder-container"
IMAGE="string-forwarder"
IMAGE_DIR="/home/mm/dev/git/docker-test/container1/"

docker container stop "${NAME}"
docker container rm "${NAME}"
docker image rm "${IMAGE}"
docker build -t "${IMAGE}" "${IMAGE_DIR}"
