#!/usr/bin/bash

# run container1 as daemon

NAME="string-forwarder-container"
IMAGE="string-forwarder"
NETWORK="docker_test_nw"

docker run -d -p 5000:5000 --network "${NETWORK}" --name "${NAME}" "${IMAGE}"
