#!/usr/bin/bash

# run mongodb container as daemon

DB_PATH="/home/mm/dev/git/docker-test/container2/data/db"
NAME="mongo-host-container"
IMAGE="mongo"
NETWORK="docker_test_nw"

docker run -d -p 27017:27017 -v "${DB_PATH}:/data/db" --network "${NETWORK}" --name "${NAME}" "${IMAGE}"
